import { tokenize } from './lexer.js';
import { parse } from './parser.js';

// Load Configs
// const config = JSON.parse(fs.readFileSync('./configs.json', 'utf8'));

let code = `
int_c base_val = 100;
int_c total = (base_val * 2) + 50;

say!!("The result is ${total}"); // Should output: "The result is 250"
`;


export function compile(sourceCode, config) {
    // 1. Raw text to Tokens
    let tokens = tokenize(sourceCode, config);

    // 2. parse tokens to get string mcfunction output
    let commands = "# This mcfunction is generated by Ophoel compiler.\n" + parse(tokens, config).join("\n");

    return commands;
}

console.log(compile(code, {}));