import { tokenize } from './lexer.js';
import { parse } from './parser.js';
import { transform } from "./transformer.js"
import { generate } from "./generator.js"
// Load Configs
// const config = JSON.parse(fs.readFileSync('./configs.json', 'utf8'));



const code =
`
mc_exec(\`as @e[tag=\${config.room_anchor_tag}, tag=\${config.room_s.tag}]\`) {
        let mut foo: int_c = config.room_s.radius;
        setblock!!(\`~ ~\${foo} ~ dirt\`);
}

`;

const config = { room_anchor_tag: "room_anchor", room_s: { radius: 7, tag: "room_s" } };

export function compile(sourceCode, config, fileName) {
    // 1. Raw text to Tokens
    let tokens = tokenize(sourceCode, config, fileName);

    // 2. parse tokens to get string mcfunction output
    let ast = parse(tokens);

    // 3. flatten and solve all compile time computations
    let processedAst = transform(ast, config);

    // 4. generate mcfunction from processed ast
    let commands = generate(processedAst);

    return ["## This mcfunction is generated by Ophoel compiler.", ...commands].join("\n");
}

// console.log("");
// console.log(tokenize(code, config, "source.oph"));
// console.log(JSON.stringify(parse(tokenize(code, config, "source.oph"))) + "\n");
// console.log(JSON.stringify(transform(parse(tokenize(code, config, "source.oph")), config)) + "\n");
// console.log(compile(code, config, "source.oph") + "\n\n");